namespace Qurre.API.Objects
{
    public enum EffectType
    {
        Amnesia,
        Asphyxiated,
        Bleeding,
        Blinded,
        Burned,
        Concussed,
        Corroding,
        Deafened,
        Decontaminating,
        Disabled,
        Ensnared,
        Exhausted,
        Flashed,
        Hemorrhage,
        Invigorated,
        BodyshotReduction,
        Poisoned,
        Scp207,
        Invisible,
        SinkHole,
        Visuals939,
        DamageReduction,
        MovementBoost,
        RainbowTaste,
        SeveredHands,
        Stained,
        Visual173Blink,
        Vitality,
    }
}